In [1]:
import pandas as pd

In [14]:
train_data = pd.read_csv('./data/train.csv',header=None)
result = pd.read_csv('./data/trainLabels.csv',header=None)
test_data = pd.read_csv('./data/test.csv',header=None)
train_data['result'] = result[0]

train_data.head()

,0,1,2,3,4,5,6,7,8,9,...,31,32,33,34,35,36,37,38,39,result
0,0.299403,-1.226624,1.498425,-1.176150,5.289853,0.208297,2.404498,1.594506,-0.051608,0.663234,...,-0.622990,-1.833057,0.293024,3.552681,0.717611,3.305972,-2.715559,-2.682409,0.101050,1
1,-1.174176,0.332157,0.949919,-1.285328,2.199061,-0.151268,-0.427039,2.619246,-0.765884,-0.093780,...,0.012037,2.038836,0.468579,-0.517657,0.422326,0.803699,1.213219,1.382932,-1.817761,0
2,1.192222,-0.414371,0.067054,-2.233568,3.658881,0.089007,0.203439,-4.219054,-1.184919,-1.240310,...,0.750054,-3.360521,0.856988,-2.751451,-1.582735,1.672246,0.656438,-0.932473,2.987436,0
3,1.573270,-0.580318,-0.866332,-0.603812,3.125716,0.870321,-0.161992,4.499666,1.038741,-1.092716,...,1.275598,-3.480110,-1.065252,2.153133,1.563539,2.767117,0.215748,0.619645,1.883397,1
4,-0.613071,-0.644204,1.112558,-0.032397,3.490142,-0.011935,1.443521,-4.290282,-1.761308,0.807652,...,-1.803473,0.518579,-0.205029,-4.744566,-1.520015,1.830651,0.870772,-1.894609,0.408332,0

In [19]:
correlations = abs(train_data.corr()['result'].sort_values())
print('Most Positive Correlations:\n', abs(correlations).sort_values().head())
high_list = list(train_data.columns[abs(correlations >= 0.05)])
high_list.remove('result')

Most Positive Correlations:
 2     0.005618
3     0.007439
10    0.010233
29    0.012022
16    0.012234
Name: result, dtype: float64

In [20]:
print('=====SVM=====')
from sklearn import svm
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

train_x = train_data[high_list]
x_train, x_test, y_train, y_test = train_test_split(train_x, result, test_size=0.1, random_state=600)
clf=svm.SVC(kernel='linear',C=0.1,gamma='auto')
clf.fit(x_train,y_train)
y_test_predict = clf.predict(x_test)
Ypred = clf.predict(x_test)
print("SVM_accuracy_score",accuracy_score(y_test, Ypred),'\n','\n')

=====SVM=====
SVM_accuracy_score 0.74

C:\Users\Administrator\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [55]:
df = pd.read_csv('./data/test.csv',header=None)
train_x = df[high_list]
df2 = pd.DataFrame(clf.predict(train_x),columns = ['Solution'])
df2.index = range(1,len(df2)+1)
df2['Id'] = df2.index
print(df2)
df2.to_csv('./prediction.csv',index=False)

      Solution    Id
1            1     1
2            0     2
3            1     3
4            0     4
5            0     5
...        ...   ...
8996         1  8996
8997         1  8997
8998         1  8998
8999         0  8999
9000         1  9000

[9000 rows x 2 columns]